---
name: Test TLS Connection on iOS
on: workflow_dispatch

env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "zulu"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :mqtt-client:cleanIosX64Test :mqtt-client:iosX64Test --tests "de.kempmobil.ktor.mqtt.ConnectionTest"
